/*
 * ResetReproDialog.xaml.cs - part of CNC Controls library for Grbl
 *
 * v0.48 / 2026-07-13 / Io Engineering (Terje Io)
 *
 */

/*

Copyright (c) 2026, Io Engineering (Terje Io)
All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

· Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.

· Redistributions in binary form must reproduce the above copyright notice, this
list of conditions and the following disclaimer in the documentation and/or
other materials provided with the distribution.

· Neither the name of the copyright holder nor the names of its contributors may
be used to endorse or promote products derived from this software without
specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/

using System;
using System.Globalization;
using System.IO;
using System.Windows;
using System.Windows.Input;
using System.Windows.Threading;
using Microsoft.Win32;
using CNC.Core;

namespace CNC.Controls
{
    /// <summary>
    /// Interaction logic for ResetReproDialog.xaml
    /// </summary>
    public partial class ResetReproDialog : Window
    {
        public ResetReproDialog(ResetReproViewModel model)
        {
            InitializeComponent();
            DialogScaling.Apply(this);

            DataContext = model;
        }

        private void Window_Loaded(object sender, RoutedEventArgs e)
        {
            var parent = Application.Current.MainWindow;

            Left = parent.Left + (parent.Width - Width) / 2d;
            Top = parent.Top + (parent.Height - Height) / 2d;

            (sender as Window).Dispatcher.Invoke(new System.Action(() =>
            {
                (sender as Window).MoveFocus(new TraversalRequest(FocusNavigationDirection.First));
            }), DispatcherPriority.ContextIdle);
        }

        void btnGenerate_Click(object sender, RoutedEventArgs e)
        {
            (DataContext as ResetReproViewModel).Generate();
        }

        void btnClose_Click(object sender, RoutedEventArgs e)
        {
            Close();
        }
    }

    // Generates a standalone .nc repro file for the "Reset during an O<n> CALL wedges the controller"
    // investigation (see the ioSender-side memory of the same name). Deliberately a plain text generator,
    // independent of GCode.File/GCodeJob, so running it never touches whatever program the user already
    // has loaded - the user loads and runs the generated file themselves, by hand, over whichever
    // connection (Serial/Telnet) they're testing.
    public class ResetReproViewModel : ViewModelBase
    {
        private double _dwell = 2d, _travel = 50d, _feed = 500d, _calls = 5d;

        public double Dwell { get { return _dwell; } set { _dwell = value; OnPropertyChanged(); } }
        public double Travel { get { return _travel; } set { _travel = value; OnPropertyChanged(); } }
        public double Feed { get { return _feed; } set { _feed = value; OnPropertyChanged(); } }
        public double Calls { get { return _calls; } set { _calls = value; OnPropertyChanged(); } }

        public void Show()
        {
            new ResetReproDialog(this) { Owner = Application.Current.MainWindow }.ShowDialog();
        }

        public void Generate()
        {
            SaveFileDialog saveDialog = new SaveFileDialog()
            {
                Filter = "GCode file (*.nc)|*.nc",
                AddExtension = true,
                DefaultExt = ".nc",
                FileName = "reset-repro-ocall.nc"
            };

            if (saveDialog.ShowDialog() != true)
                return;

            try
            {
                using (StreamWriter stream = new StreamWriter(saveDialog.FileName))
                {
                    var inv = CultureInfo.InvariantCulture;
                    int calls = Math.Max(1, (int)Calls);

                    stream.WriteLine("; Reset-during-O<>-CALL repro test, generated by ioSender's Generate reset test case dialog.");
                    stream.WriteLine("; Purpose: reproduce the controller wedge seen when Reset lands while an O<n> CALL");
                    stream.WriteLine("; subroutine is executing (or mid-motion generally).");
                    stream.WriteLine("; ");
                    stream.WriteLine("; IMPORTANT: grblHAL only allows O-word flow control (sub/call/endsub) when the");
                    stream.WriteLine("; controller is reading from a file-backed stream (hal.stream.file != NULL) - loading");
                    stream.WriteLine("; this as a normal job and streaming it over Serial/Telnet fails immediately with");
                    stream.WriteLine("; error:80 (Flow statement only allowed in filesystem macro), before Reset even");
                    stream.WriteLine("; comes into it. UPLOAD this file to SD Card / the on-board filesystem first, then");
                    stream.WriteLine("; RUN it from ioSender's SD Card tab - that path runs the file through grblHAL's own");
                    stream.WriteLine("; file reader, which is what satisfies the hal.stream.file requirement.");
                    stream.WriteLine("; ");
                    stream.WriteLine("; Once running from SD Card, press RESET partway through one of the o100 calls below");
                    stream.WriteLine("; - the dwells either side of the move give a wide window to time it. Run the SAME");
                    stream.WriteLine("; file again over the other connection type (Serial vs Telnet) to check whether the");
                    stream.WriteLine("; wedge is transport-dependent.");
                    stream.WriteLine();
                    stream.WriteLine("G90");
                    stream.WriteLine("G21");
                    stream.WriteLine();
                    stream.WriteLine("o100 sub");
                    stream.WriteLine(string.Format(inv, "  G4 P{0}", Dwell));
                    stream.WriteLine(string.Format(inv, "  G1 X{0} F{1}", Travel, Feed));
                    stream.WriteLine(string.Format(inv, "  G4 P{0}", Dwell));
                    stream.WriteLine(string.Format(inv, "  G1 X0 F{0}", Feed));
                    stream.WriteLine(string.Format(inv, "  G4 P{0}", Dwell));
                    stream.WriteLine("o100 endsub");
                    stream.WriteLine();

                    for (int i = 0; i < calls; i++)
                        stream.WriteLine("o100 call");

                    stream.WriteLine();
                    stream.WriteLine("M30");
                }

                AppDialogs.Show(Application.Current.MainWindow, "Test case written to:" + Environment.NewLine + saveDialog.FileName + Environment.NewLine + Environment.NewLine +
                    "Upload it to SD Card / the on-board filesystem and run it from the SD Card tab - loading it as a normal job will fail with error:80.",
                    "Generate reset test case", MessageBoxButton.OK, MessageBoxImage.Information);
            }
            catch (Exception ex)
            {
                AppDialogs.Show(Application.Current.MainWindow, ex.Message, "Generate reset test case", MessageBoxButton.OK, MessageBoxImage.Exclamation);
            }
        }
    }
}
