#!/usr/bin/env python3
"""gen-sim-macros.py - regenerate the Simulator repo's embedded ATC macro strings.

Reads ioSender's canonical ATC macros (macros/tc.macro, pcorner.macro, pvisecorner.macro - the
same files AtcMacros.cs embeds to provision a real controller) and emits a C header,
src/embedded_macros.h, in the sibling Simulator repo. driver.c writes these into littlefs at boot
(sim_seed_atc_macros), so every simulator this repo builds is ATC-macro-ready out of the box -
matching a correctly-provisioned real machine, with no runtime transfer step needed.

Re-run this whenever macros/*.macro changes and the Simulator repo needs to pick it up (idempotent -
re-running with unchanged sources produces a byte-identical header).

Usage: python tools/gen-sim-macros.py [--simulator-repo PATH]
"""

import argparse
import os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

MACROS = ["tc.macro", "pcorner.macro", "pvisecorner.macro"]


def c_string_literal(text):
    """One adjacent-string-literal C line per input line (avoids literal-length limits, diffs cleanly)."""
    lines = text.replace('\r\n', '\n').split('\n')
    out = []
    for ln in lines:
        escaped = ln.replace('\\', '\\\\').replace('"', '\\"')
        out.append('    "' + escaped + '\\n"')
    return '\n'.join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--simulator-repo', default=os.path.join(os.path.dirname(REPO), 'Simulator'))
    args = ap.parse_args()

    dest = os.path.join(args.simulator_repo, 'src', 'embedded_macros.h')
    if not os.path.isdir(os.path.dirname(dest)):
        raise SystemExit('Simulator repo src/ not found at ' + os.path.dirname(dest) + ' - pass --simulator-repo')

    parts = ['// embedded_macros.h - GENERATED by ioSender/tools/gen-sim-macros.py - do not hand-edit.',
             '// Source: ioSender/macros/*.macro (the same files AtcMacros.cs provisions onto a real',
             '// controller). Re-run the generator after changing them.',
             '',
             '#ifndef EMBEDDED_MACROS_H',
             '#define EMBEDDED_MACROS_H',
             '']

    for name in MACROS:
        path = os.path.join(REPO, 'macros', name)
        with open(path, 'r', encoding='utf-8') as f:
            content = f.read()
        ident = 'embedded_macro_' + name.replace('.macro', '').replace('-', '_')
        parts.append('static const char *' + ident + ' =')
        parts.append(c_string_literal(content) + ';')
        parts.append('')

    parts.append('#endif // EMBEDDED_MACROS_H')
    parts.append('')

    with open(dest, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(parts))

    print('wrote', dest)


if __name__ == '__main__':
    main()
