fatal: ambiguous argument 'v2\pr\start-job-dynamic-mode;.github\workflows\beta-release.yml': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
